
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author keyli
 */
public class Clientes extends javax.swing.JFrame {

String nombre, paterno, materno, direccion, telefono, genero, correo;
//sirve para almacenar los registros en las tablas
    DefaultTableModel model, datos;
    /**
     * Creates new form interfaz
     */
    public Clientes() {
        initComponents();
        limpiar();
        bloquear();
        desbloquear();
        cargar("");
    }
    
    //evento para cargar los registros guardados en la tabla 
    void cargar(String valor){
        
        String [] titulos ={"idcte","nombre","apepat","apemat","genero","telefono","correo","direccion"}; 
        String [] registros = new String[8];
        String sql = "SELECT * FROM usuario WHERE CONCAT(nombre) like '%"+valor+"%'";
        model = new DefaultTableModel(null, titulos);
        
        
        conectar cc = new conectar();
        Connection cn =cc.conexion();
        
        try {
            Statement  st =cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                registros[0]=rs.getString("idcte");
                registros[1]=rs.getString("nombre");
                registros[2]=rs.getString("apepat");
                registros[3]=rs.getString("apemat");
                registros[4]=rs.getString("genero");
                registros[5]=rs.getString("telefono");
                registros[6]=rs.getString("correo");
                registros[7]=rs.getString("direccion");
                
                model.addRow(registros);
            
                tdatos.setModel(model);
                
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    
    } 
    
void limpiar(){
    idcte.setText("");
    txtnombre.setText("");
    cbgenero.setSelectedIndex(0);
    txtapepat.setText("");
    txtapemat.setText("");
    txttel.setText("");
    txtdireccion.setText("");
    txtcorreo.setText("");
   }
    
    void bloquear(){
    idcte.setEnabled(false);
    txtnombre.setEnabled(false);
    txtapepat.setEnabled(false);
    txtapemat.setEnabled(false);
    txttel.setEnabled(false);
    txtdireccion.setEnabled(false);
    cbgenero.setEnabled(false);
    txtcorreo.setEnabled(false);
    btnuevo.setEnabled(true);
    btguardar.setEnabled(false);
    btcancelar.setEnabled(false);
    
    
    }
void desbloquear(){
    idcte.setEnabled(false);
    txtnombre.setEnabled(true);
    txtapepat.setEnabled(true);
    txtapemat.setEnabled(true);
    txttel.setEnabled(true);
    txtdireccion.setEnabled(true);
    cbgenero.setEnabled(true);
    txtcorreo.setEnabled(true);
    btnuevo.setEnabled(true);
    btguardar.setEnabled(true);
    btcancelar.setEnabled(true);
       
}

void bloqguardar(){
    btguardar.setEnabled(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbgenero = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdatos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnuevo = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        txtapemat = new javax.swing.JTextField();
        txtapepat = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        idcte = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bteliminar = new javax.swing.JButton();
        btmodificar = new javax.swing.JButton();
        btmostrar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();

        jButton4.setText("jButton4");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/imagenes/10_1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cbgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgeneroActionPerformed(evt);
            }
        });
        getContentPane().add(cbgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 100, -1));

        tdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tdatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tdatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 610, 170));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Datos de Cliente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        btnuevo.setText("Nuevo");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        btguardar.setText("Guardar");
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        btsalir.setText("Salir");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        jLabel5.setText("Id");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel7.setText("Apellido P");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setText("Nombre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel8.setText("Apellido M");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel11.setText("Teléfono");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel10.setText("Dirección");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel9.setText("Género");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel12.setText("Correo E.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 100, -1));

        txtapemat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapematActionPerformed(evt);
            }
        });
        getContentPane().add(txtapemat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 110, -1));

        txtapepat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapepatActionPerformed(evt);
            }
        });
        getContentPane().add(txtapepat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, -1));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 110, -1));

        idcte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcteActionPerformed(evt);
            }
        });
        getContentPane().add(idcte, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 110, -1));

        txttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelActionPerformed(evt);
            }
        });
        getContentPane().add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 100, -1));

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/imagenes/bg.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 330));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/imagenes/10_1.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 330));

        bteliminar.setText("Eliminar");
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });
        getContentPane().add(bteliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 90, -1));

        btmodificar.setText("Modificar");
        btmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 100, -1));

        btmostrar.setText("Mostrar todo");
        btmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabel13.setText("Buscar");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 20));

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_btsalirActionPerformed

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
    desbloquear();
    limpiar();
    txtnombre.requestFocus();
    }//GEN-LAST:event_btnuevoActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
    bloquear();
    }//GEN-LAST:event_btcancelarActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
     txtnombre.requestFocus();
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtapepatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapepatActionPerformed
        txtapepat.requestFocus();
    }//GEN-LAST:event_txtapepatActionPerformed

    private void txtapematActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapematActionPerformed
        txtapemat.requestFocus();
    }//GEN-LAST:event_txtapematActionPerformed

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
        txttel.requestFocus();
    }//GEN-LAST:event_txttelActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        txtdireccion.requestFocus();
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        txtcorreo.requestFocus();
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void cbgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgeneroActionPerformed
        cbgenero.requestFocus();
    }//GEN-LAST:event_cbgeneroActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
        
        conectar c = new conectar();
            Connection cn = c.conexion();
            
            String sql = "";
            nombre = txtnombre.getText();
            paterno = txtapepat.getText();
            materno = txtapemat.getText();
            genero = cbgenero.getSelectedItem().toString();
            telefono = txttel.getText();
            correo = txtcorreo.getText();
            direccion = txtdireccion.getText();
            sql= "INSERT INTO usuario(nombre, apepat, apemat, genero, telefono,correo, direccion) VALUES (?, ?, ?, ?,?, ?, ?)";
            try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1,nombre);
            pst.setString(2, paterno);
            pst.setString(3, materno);
            pst.setString(4,genero);
            pst.setString(5,telefono);
            pst.setString(6,correo);
            pst.setString(7,direccion);
            int n = pst.executeUpdate();
            if(n>0)
               JOptionPane.showMessageDialog(null, "Registro guardado exitosamente");
            desbloquear();
            cargar("");
            
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }//GEN-LAST:event_btguardarActionPerformed

    private void idcteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcteActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
     conectar c = new conectar();
     Connection cn = c.conexion();

        try{
        int fila = tdatos.getSelectedRow();
        String sql = "delete from usuario where idcte =" + tdatos.getValueAt(fila, 0);
        Statement  st =cn.createStatement();
        
        //PreparedStatement pst = cn.prepareStatement(sql);
        int n = st.executeUpdate(sql);
        
        if(n>0){
        cargar("");  
        //desbloquear();
        JOptionPane.showMessageDialog(null, "DATOS ELIMINADOS");
        
        limpiar();
        
        } 
        
        }catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        
        }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarActionPerformed
         conectar c = new conectar();
         Connection cn = c.conexion();
            
        try{
            String sql = "UPDATE usuario SET nombre=?, apepat=?, apemat=?, genero=?, telefono=?, correo=?, direccion=? " +
                    "WHERE idcte=?";
            int fila = tdatos.getSelectedRow();
            String dato =(String) tdatos.getValueAt(fila, 0);
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, txtnombre.getText());
            pst.setString(2, txtapepat.getText());
            pst.setString(3, txtapemat.getText());
            pst.setString(4, cbgenero.getSelectedItem().toString());
            pst.setString(5, txttel.getText());
            pst.setString(6, txtcorreo.getText());
            pst.setString(7, txtdireccion.getText());
            pst.setString(8, dato);
            int n = pst.executeUpdate();
            if(n>0){
               
               cargar("");
               limpiar();
               JOptionPane.showMessageDialog(null, "Datos Modificados");
            }
        } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
            
                    
                
            }
    }//GEN-LAST:event_btmodificarActionPerformed

    private void tdatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdatosMouseClicked
     int filasele = tdatos.getSelectedRow();
     idcte.setText(tdatos.getValueAt(filasele, 0 ).toString());
     txtnombre.setText(tdatos.getValueAt(filasele, 1 ).toString());
     txtapepat.setText(tdatos.getValueAt(filasele, 2 ).toString());
     txtapemat.setText(tdatos.getValueAt(filasele, 3 ).toString());
     cbgenero.setSelectedItem(tdatos.getValueAt(filasele, 4 ).toString());
     txttel.setText(tdatos.getValueAt(filasele, 5 ).toString());
     txtcorreo.setText(tdatos.getValueAt(filasele, 6).toString());
     txtdireccion.setText(tdatos.getValueAt(filasele, 7 ).toString());
     filas = filasele;
     desbloquear();
    }//GEN-LAST:event_tdatosMouseClicked

    private void btmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmostrarActionPerformed
        cargar("");
    }//GEN-LAST:event_btmostrarActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
         cargar(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
       
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        cargar(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btguardar;
    private javax.swing.JButton btmodificar;
    private javax.swing.JButton btmostrar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JButton btsalir;
    private javax.swing.JComboBox<String> cbgenero;
    private javax.swing.JTextField idcte;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tdatos;
    private javax.swing.JTextField txtapemat;
    private javax.swing.JTextField txtapepat;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables

    int filas;

    
   /* private void btsalir() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
*/
    private void cargar() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
