
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class Productos extends javax.swing.JFrame {
String nombre, codprod, marca, caract, proveedor, cantidad, categoria, preciocom, preciovt;
//sirve para almacenar los registros en las tablas
    DefaultTableModel model, datos;
    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        limpiar();
        bloquear();
        desbloquear();
        cargar("");
    }

    //evento para cargar los registros guardados en la tabla 
    void cargar(String valor){
        
        String [] titulos ={"idproducto","nombre","codprod","categoria","marca","caracteristicas","proveedor","preciocom","preciovt","cantidad"}; 
        String [] registros = new String[10];
        String sql = "SELECT * FROM productos WHERE CONCAT(nombre) like '%"+valor+"%'";
        model = new DefaultTableModel(null, titulos);
        
        
        conectar cc = new conectar();
        Connection cn =cc.conexion();
        
        try {
            Statement  st =cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                registros[0]=rs.getString("idproducto");
                registros[1]=rs.getString("nombre");
                registros[2]=rs.getString("codprod");
                registros[3]=rs.getString("categoria");
                registros[4]=rs.getString("marca");
                registros[5]=rs.getString("caracteristicas");
                registros[6]=rs.getString("proveedor");
                registros[7]=rs.getString("preciocom");
                registros[8]=rs.getString("preciovt");
                registros[9]=rs.getString("cantidad");               
                model.addRow(registros);
            
                tdatosprod.setModel(model);
                
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    
    } 
    
    void limpiar(){
    idproducto.setText("");
    txtproducto.setText("");
    cbcategoria.setSelectedIndex(0);
    txtcodprod.setText("");
    txtmarca.setText("");
    txtcaracteristicas.setText("");
    txtproveedor.setText("");
    txtpreciocom.setText("");
    txtpreciovt.setText("");
    txtcantidad.setText("");
   }
    
    void bloquear(){
    idproducto.setEnabled(false);
    txtproducto.setEnabled(false);
    cbcategoria.setEnabled(false);
    txtcodprod.setEnabled(false);
    txtmarca.setEnabled(false);
    txtcaracteristicas.setEnabled(false);
    txtproveedor.setEnabled(false);
    txtpreciocom.setEnabled(false);
    txtpreciovt.setEnabled(false);
    txtcantidad.setEnabled(false);
    btnuevo.setEnabled(true);
    btguardar.setEnabled(false);
    btcancelar.setEnabled(false);
    
    
    }
void desbloquear(){
    idproducto.setEnabled(false);
    txtproducto.setEnabled(true);
    txtcodprod.setEnabled(true);
    txtmarca.setEnabled(true);
    txtcaracteristicas.setEnabled(true);
    txtproveedor.setEnabled(true);
    cbcategoria.setEnabled(true);
    txtpreciocom.setEnabled(true);
    txtpreciovt.setEnabled(true);
    txtcantidad.setEnabled(true);
    btnuevo.setEnabled(true);
    btguardar.setEnabled(true);
    btcancelar.setEnabled(true);
       
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idproducto = new javax.swing.JTextField();
        txtproducto = new javax.swing.JTextField();
        txtcodprod = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        txtcaracteristicas = new javax.swing.JTextField();
        txtproveedor = new javax.swing.JTextField();
        txtpreciocom = new javax.swing.JTextField();
        txtpreciovt = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        btnuevo = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();
        cbcategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdatosprod = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos de producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel3.setText("Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setText("Producto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel5.setText("Cod. Producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setText("Categoría");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel7.setText("Marca");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel8.setText("Proveedor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jLabel9.setText("Precio Compra");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel10.setText("Precio Venta");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel11.setText("Cant. Disponible");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabel12.setText("Características");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(idproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 170, -1));

        txtproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 170, -1));

        txtcodprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodprodActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 170, -1));

        txtmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmarcaActionPerformed(evt);
            }
        });
        getContentPane().add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 170, -1));

        txtcaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaracteristicasActionPerformed(evt);
            }
        });
        getContentPane().add(txtcaracteristicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 170, -1));

        txtproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproveedorActionPerformed(evt);
            }
        });
        getContentPane().add(txtproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 160, -1));

        txtpreciocom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreciocomActionPerformed(evt);
            }
        });
        getContentPane().add(txtpreciocom, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 160, -1));

        txtpreciovt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreciovtActionPerformed(evt);
            }
        });
        getContentPane().add(txtpreciovt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 160, -1));

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 160, -1));

        btnuevo.setText("Nuevo");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 70, -1));

        btguardar.setText("Guardar");
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        btsalir.setText("Salir");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 70, -1));

        cbcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Redes", "Cómputo", "Consumibles", "Torres", "Seguridad", "Networking", "Cámaras", "Alarmas", "Radiocomunicación" }));
        cbcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cbcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/imagenes/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 330));

        jLabel13.setText("Buscar");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 170, -1));

        jButton1.setText("Mostrar todo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 90, -1));

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 90, -1));

        tdatosprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tdatosprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdatosprodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tdatosprod);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 600, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
    desbloquear();
    limpiar();
    txtproducto.requestFocus();
    }//GEN-LAST:event_btnuevoActionPerformed

    private void txtproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductoActionPerformed
        txtproducto.requestFocus();
    }//GEN-LAST:event_txtproductoActionPerformed

    private void txtcodprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodprodActionPerformed
        txtcodprod.requestFocus();
    }//GEN-LAST:event_txtcodprodActionPerformed

    private void cbcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcategoriaActionPerformed
       cbcategoria.requestFocus();
    }//GEN-LAST:event_cbcategoriaActionPerformed

    private void txtmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmarcaActionPerformed
        txtmarca.requestFocus();
    }//GEN-LAST:event_txtmarcaActionPerformed

    private void txtcaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaracteristicasActionPerformed
        txtcaracteristicas.requestFocus();
    }//GEN-LAST:event_txtcaracteristicasActionPerformed

    private void txtproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproveedorActionPerformed
        txtproveedor.requestFocus();
    }//GEN-LAST:event_txtproveedorActionPerformed

    private void txtpreciocomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreciocomActionPerformed
        txtpreciocom.requestFocus();
    }//GEN-LAST:event_txtpreciocomActionPerformed

    private void txtpreciovtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreciovtActionPerformed
        txtpreciovt.requestFocus();
    }//GEN-LAST:event_txtpreciovtActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        txtcantidad.requestFocus();
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
            conectar c = new conectar();
            Connection cn = c.conexion();
            
            String sql = "";
            nombre = txtproducto.getText();
            codprod = txtcodprod.getText();
            categoria = cbcategoria.getSelectedItem().toString();
            marca = txtmarca.getText();
            caract = txtcaracteristicas.getText();
            proveedor = txtproveedor.getText();
            preciocom = txtpreciocom.getText();
            preciovt = txtpreciovt.getText();
            cantidad = txtcantidad.getText();
            
            sql= "INSERT INTO productos(nombre, codprod, categoria, marca, caracteristicas,proveedor, preciocom, preciovt, cantidad) VALUES (?, ?, ?, ?,?, ?, ?, ?, ?)";
            try {
             
                PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, nombre);
            pst.setString(2, codprod);
            pst.setString(3, categoria);
            pst.setString(4, marca);
            pst.setString(5, caract);
            pst.setString(6, proveedor);
            pst.setString(7, preciocom);
            pst.setString(8, preciovt);
            pst.setString(9, cantidad);
            
            int n = pst.executeUpdate();
            if(n>0)
               JOptionPane.showMessageDialog(null, "Registro guardado exitosamente");
            desbloquear();
            cargar("");
            
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }//GEN-LAST:event_btguardarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        bloquear();
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btsalirActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        cargar(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        cargar(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargar("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        conectar c = new conectar();
        Connection cn = c.conexion();

        try{
        int fila = tdatosprod.getSelectedRow();
        String sql = "delete from productos where idproducto =" + tdatosprod.getValueAt(fila, 0);
        Statement  st =cn.createStatement();
        
        //PreparedStatement pst = cn.prepareStatement(sql);
        int n = st.executeUpdate(sql);
        
        if(n>0){
        cargar("");  
        //desbloquear();
        JOptionPane.showMessageDialog(null, "DATOS ELIMINADOS");
        
        limpiar();
        
        } 
        
        }catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        conectar c = new conectar();
         Connection cn = c.conexion();
            
        try{
            String sql = "UPDATE productos SET nombre=?, codprod=?, categoria=?, marca=?, caracteristicas=?, proveedor=?, preciocom=?, preciovt=?, cantidad=? " +
                    "WHERE idproducto=?";
            int fila = tdatosprod.getSelectedRow();
            String dato =(String) tdatosprod.getValueAt(fila, 0);
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, txtproducto.getText());
            pst.setString(2, txtcodprod.getText());
            pst.setString(3, cbcategoria.getSelectedItem().toString());
            pst.setString(4, txtmarca.getText());
            pst.setString(5, txtcaracteristicas.getText());
            pst.setString(6, txtproveedor.getText());
            pst.setString(7, txtpreciocom.getText());
            pst.setString(8, txtpreciovt.getText());
            pst.setString(9, txtcantidad.getText());
            pst.setString(10, dato);
            int n = pst.executeUpdate();
            if(n>0){
               
               cargar("");
               limpiar();
               JOptionPane.showMessageDialog(null, "Datos Modificados");
            }
        } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
            
                    
                
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tdatosprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdatosprodMouseClicked
     int filasele = tdatosprod.getSelectedRow();
     idproducto.setText(tdatosprod.getValueAt(filasele, 0 ).toString());
     txtproducto.setText(tdatosprod.getValueAt(filasele, 1 ).toString());
     txtcodprod.setText(tdatosprod.getValueAt(filasele, 2 ).toString());
     cbcategoria.setSelectedItem(tdatosprod.getValueAt(filasele, 3 ).toString());
     txtmarca.setText(tdatosprod.getValueAt(filasele, 4 ).toString());
     txtcaracteristicas.setText(tdatosprod.getValueAt(filasele, 5 ).toString());
     txtproveedor.setText(tdatosprod.getValueAt(filasele, 6 ).toString());
     txtpreciocom.setText(tdatosprod.getValueAt(filasele, 7).toString());
     txtpreciovt.setText(tdatosprod.getValueAt(filasele, 8 ).toString());
     txtcantidad.setText(tdatosprod.getValueAt(filasele, 9 ).toString());
     filas = filasele;
     desbloquear();
    }//GEN-LAST:event_tdatosprodMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btguardar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JButton btsalir;
    private javax.swing.JComboBox<String> cbcategoria;
    private javax.swing.JTextField idproducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tdatosprod;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcaracteristicas;
    private javax.swing.JTextField txtcodprod;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtpreciocom;
    private javax.swing.JTextField txtpreciovt;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txtproveedor;
    // End of variables declaration//GEN-END:variables

int filas;

}
