
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class Proveedores extends javax.swing.JFrame {
String nombre, paterno, materno, empresa, producto, direccion, telefono, genero, correo;
//sirve para almacenar los registros en las tablas
    DefaultTableModel model, datos;
    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        limpiar();
        bloquear();
        desbloquear();
        cargar("");
    }

    //evento para cargar los registros guardados en la tabla 
    void cargar(String valor){
        
        String [] titulos ={"idproveedor","nombre","apepat","apemat","empresa","telefono","producto","direccion","correo"}; 
        String [] registros = new String[9];
        String sql = "SELECT * FROM proveedores WHERE CONCAT(nombre) like '%"+valor+"%'";
        model = new DefaultTableModel(null, titulos);
        
        
        conectar cc = new conectar();
        Connection cn =cc.conexion();
        
        try {
            Statement  st =cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                registros[0]=rs.getString("idproveedor");
                registros[1]=rs.getString("nombre");
                registros[2]=rs.getString("apepat");
                registros[3]=rs.getString("apemat");
                registros[4]=rs.getString("empresa");
                registros[5]=rs.getString("telefono");
                registros[6]=rs.getString("producto");
                registros[7]=rs.getString("direccion");
                registros[8]=rs.getString("correo");
                
                model.addRow(registros);
            
                tdatos.setModel(model);
                
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    
    } 
    
   void limpiar(){
    idproveedor.setText("");
    txtnombre.setText("");
    txtapepat.setText("");
    txtapemat.setText("");
    txttel.setText("");
    txtdireccion.setText("");
    txtcorreo.setText("");
    txtempresa.setText("");
    txtproducto.setText("");
   }
    
    void bloquear(){
    idproveedor.setEnabled(false);
    txtnombre.setEnabled(false);
    txtapepat.setEnabled(false);
    txtapemat.setEnabled(false);
    txttel.setEnabled(false);
    txtdireccion.setEnabled(false);
    txtempresa.setEnabled(false);
    txtproducto.setEnabled(false);
    txtcorreo.setEnabled(false);
    btnuevo.setEnabled(true);
    btguardar.setEnabled(false);
    btcancelar.setEnabled(false);
    
    
    }
void desbloquear(){
    idproveedor.setEnabled(false);
    txtnombre.setEnabled(true);
    txtapepat.setEnabled(true);
    txtapemat.setEnabled(true);
    txttel.setEnabled(true);
    txtdireccion.setEnabled(true);
    txtempresa.setEnabled(true);
    txtproducto.setEnabled(true);
    txtcorreo.setEnabled(true);
    btnuevo.setEnabled(true);
    btguardar.setEnabled(true);
    btcancelar.setEnabled(true);
       
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idproveedor = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapepat = new javax.swing.JTextField();
        txtapemat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtempresa = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtproducto = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        btnuevo = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdatos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos de proveedores");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel3.setText("Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel5.setText("Apellido P");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel6.setText("Apellido M");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));
        getContentPane().add(idproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, -1));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 110, -1));

        txtapepat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapepatActionPerformed(evt);
            }
        });
        getContentPane().add(txtapepat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 110, -1));

        txtapemat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapematActionPerformed(evt);
            }
        });
        getContentPane().add(txtapemat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 110, -1));

        jLabel8.setText("Empresa");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel9.setText("Teléfono");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel10.setText("Dirección");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel11.setText("Producto");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        txtempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempresaActionPerformed(evt);
            }
        });
        getContentPane().add(txtempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 130, -1));

        txttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelActionPerformed(evt);
            }
        });
        getContentPane().add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 130, -1));

        txtproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 130, -1));

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 130, -1));

        btnuevo.setText("Nuevo");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        btguardar.setText("Guardar");
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        btsalir.setText("Salir");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jLabel12.setText("Correo E.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/imagenes/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 673, 320));

        tdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tdatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tdatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 670, 190));

        jLabel7.setText("Buscar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 140, -1));

        jButton1.setText("Mostrar todo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 110, -1));

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 100, -1));

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        txtnombre.requestFocus();
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtapepatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapepatActionPerformed
        txtapepat.requestFocus();
    }//GEN-LAST:event_txtapepatActionPerformed

    private void txtapematActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapematActionPerformed
       txtapemat.requestFocus();
    }//GEN-LAST:event_txtapematActionPerformed

    private void txtempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempresaActionPerformed
       txtempresa.requestFocus();
    }//GEN-LAST:event_txtempresaActionPerformed

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
       txttel.requestFocus();
    }//GEN-LAST:event_txttelActionPerformed

    private void txtproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductoActionPerformed
       txtproducto.requestFocus();
    }//GEN-LAST:event_txtproductoActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        txtdireccion.requestFocus();
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
    desbloquear();
    limpiar();
    txtnombre.requestFocus();
    }//GEN-LAST:event_btnuevoActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
    txtcorreo.requestFocus();
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
       conectar c = new conectar();
            Connection cn = c.conexion();
            
            String sql = "";
            nombre = txtnombre.getText();
            paterno = txtapepat.getText();
            materno = txtapemat.getText();
            empresa = txtempresa.getText();
            producto = txtproducto.getText();
            telefono = txttel.getText();
            correo = txtcorreo.getText();
            direccion = txtdireccion.getText();
            sql= "INSERT INTO proveedores(nombre, apepat, apemat, empresa, telefono, producto, direccion, correo) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1,nombre);
            pst.setString(2, paterno);
            pst.setString(3, materno);
            pst.setString(4,empresa);
            pst.setString(5,telefono);
            pst.setString(6,producto);
            pst.setString(7,direccion);
            pst.setString(8,correo);
            int n = pst.executeUpdate();
            if(n>0)
               JOptionPane.showMessageDialog(null, "Registro guardado exitosamente");
            desbloquear();
            cargar("");
            
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btguardarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
       bloquear();
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_btsalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargar("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        conectar c = new conectar();
     Connection cn = c.conexion();

        try{
        int fila = tdatos.getSelectedRow();
        String sql = "delete from proveedores where idproveedor =" + tdatos.getValueAt(fila, 0);
        Statement  st =cn.createStatement();
        
        //PreparedStatement pst = cn.prepareStatement(sql);
        int n = st.executeUpdate(sql);
        
        if(n>0){
        cargar("");  
        //desbloquear();
        JOptionPane.showMessageDialog(null, "DATOS ELIMINADOS");
        
        limpiar();
        
        } 
        
        }catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        conectar c = new conectar();
         Connection cn = c.conexion();
            
        try{
            String sql = "UPDATE proveedores SET nombre=?, apepat=?, apemat=?, empresa=?, telefono=?, producto=?, direccion=?, correo=? " +
                    "WHERE idproveedor=?";
            int fila = tdatos.getSelectedRow();
            String dato =(String) tdatos.getValueAt(fila, 0);
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, txtnombre.getText());
            pst.setString(2, txtapepat.getText());
            pst.setString(3, txtapemat.getText());
            pst.setString(4, txtempresa.getText());
            pst.setString(5, txttel.getText());
            pst.setString(6, txtproducto.getText());
            pst.setString(7, txtdireccion.getText());
            pst.setString(8, txtcorreo.getText());
            pst.setString(9, dato);
            int n = pst.executeUpdate();
            if(n>0){
               
               cargar("");
               limpiar();
               JOptionPane.showMessageDialog(null, "Datos Modificados");
            }
        } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
            
                    
                
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        cargar(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        cargar(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void tdatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdatosMouseClicked
     int filasele = tdatos.getSelectedRow();
     idproveedor.setText(tdatos.getValueAt(filasele, 0 ).toString());
     txtnombre.setText(tdatos.getValueAt(filasele, 1 ).toString());
     txtapepat.setText(tdatos.getValueAt(filasele, 2 ).toString());
     txtapemat.setText(tdatos.getValueAt(filasele, 3 ).toString());
     txtempresa.setText(tdatos.getValueAt(filasele, 4 ).toString());
     txttel.setText(tdatos.getValueAt(filasele, 5 ).toString());
     txtproducto.setText(tdatos.getValueAt(filasele, 6 ).toString());
     txtdireccion.setText(tdatos.getValueAt(filasele, 7).toString());
     txtcorreo.setText(tdatos.getValueAt(filasele, 8 ).toString());
     filas = filasele;
     desbloquear();
    }//GEN-LAST:event_tdatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btguardar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JButton btsalir;
    private javax.swing.JTextField idproveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tdatos;
    private javax.swing.JTextField txtapemat;
    private javax.swing.JTextField txtapepat;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtempresa;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables

    int filas;
}
